export { default as JobDetailPage } from './JobDetail'
export { default as RecruitmentDashboardPage } from './JobList'
export { default as EmptyRecordPage } from './EmptyRecord'
export { default as CreateJobPage } from './CreateJob'
export { default as CreateCandidatePage } from './CreateCandidate'
