export { default as SettingLayout } from './Layout'
export { default as GeneralPage } from './General'

export { default as AssetPage } from './Asset'
export { default as WorkLocationPage } from './WorkLocation'
export { default as SkillSetPage } from './SkillSet'
export { default as BenefitPackagePage } from './BenefitPackage'
export { default as OnboardingPage } from './Onboarding'
export { default as DepartmentPage } from './Department'
export { default as DocumentPolicyPage } from './DocumentPolicy'
export { default as PipelineStagesPage } from './PipelineStages'

export { default as ModulesPage } from './Modules'
export { default as ExpensesPage } from './Expenses'
export { default as LocalizationPage } from './Localization'
export { default as RolesPermissionsPage } from './RolesPermissions'
export { default as PersonalizationPage } from './Personalization'
export { default as NotificationsPage } from './Notifications'
export { default as CommunicationPage } from './Communication'
export { default as BackupRecoveryPage } from './BackupRecovery'
export { default as AdvancedPage } from './Advanced'
