import { Person } from 'type/search'
import APIClient from '../api/apiClient'

export const globalSearchRequest = ({ search }: { search: string }) =>
	APIClient.get('/navbar/search', { params: { search } })

// export const globalSearchRequest = ({ search }: { search: string }) => {
// 	return new Promise((resolve) => {
// 		setTimeout(() => {
// 			resolve({
// 				data: {
// 					data: {
// 						employees: [
// 							{
// 								id: 10,
// 								uuid: '3ba5a91c-49da-4589-b59a-7c5397eea549',
// 								organization_id: 44,
// 								designation: null,
// 								parent_id: null,
// 								first_name: 'Umair',
// 								last_name: 'Abbas',
// 								photo: 'https://ik.imagekit.io/peopleplus/300-3_iybnpAZSNA.jpg',
// 								dob: '1970-01-01',
// 								gender: 'male',
// 								cnic: '123456',
// 								email: 'umiar1@gmail.com',
// 								phone_number: null,
// 								street_address: 'Dolore non est animi',
// 								city: 'Esse consectetur e',
// 								state: 'Non voluptate sit i',
// 								postcode: '12345',
// 								country_id: 25,
// 								user_id: '6',
// 								employee_id: '12',
// 								employee_status: 'active',
// 								employee_type: 'full-time',
// 								probation_end_date: '1970-01-01',
// 								joining_date: '1970-01-01',
// 								termination_date: '1970-01-01',
// 								job_title: 'Job title',
// 								department_id: null,
// 								role: null,
// 								work_location_id: null,
// 								salary: null,
// 								pay_frequency: null,
// 								currency: 'pkr',
// 								degree: null,
// 								institute: null,
// 								about: null,
// 								working_hours: null,
// 								working_days: null,
// 								time_zone: null,
// 								custom_fields: null,
// 								created_at: '2024-02-28T10:17:56.000000Z',
// 								updated_at: '2024-03-12T14:13:47.000000Z',
// 								is_top_level: 0,
// 							},
// 							{
// 								id: 29,
// 								uuid: '0775c88d-a4bc-4872-94ed-7d5cae4db561',
// 								organization_id: 44,
// 								designation: null,
// 								parent_id: null,
// 								first_name: 'Yoshio',
// 								last_name: 'Mack',
// 								photo: 'https://ik.imagekit.io/peopleplus/300-17_n8f3BRLDy.jpg',
// 								dob: '1972-03-15',
// 								gender: 'male',
// 								cnic: '1231234345324',
// 								email: 'tivupy@mailinator.com',
// 								phone_number: null,
// 								street_address: 'st# 20',
// 								city: 'Bezu',
// 								state: 'utha',
// 								postcode: '50003',
// 								country_id: 22,
// 								user_id: '25',
// 								employee_id: '6723',
// 								employee_status: 'active',
// 								employee_type: 'part-time',
// 								probation_end_date: '2024-03-22',
// 								joining_date: '2024-03-12',
// 								termination_date: '2024-03-31',
// 								job_title: 'HR',
// 								department_id: 243,
// 								role: null,
// 								work_location_id: null,
// 								salary: '230000',
// 								pay_frequency: 'biannully',
// 								currency: 'pkr',
// 								degree: 'BS-Business',
// 								institute: 'Aut vero assumenda e',
// 								about: 'Deserunt suscipit qu',
// 								working_hours: '9am to 10pm',
// 								working_days: '["Thursday","Friday","Tuesday","Saturday"]',
// 								time_zone: null,
// 								custom_fields: null,
// 								created_at: '2024-03-12T14:24:29.000000Z',
// 								updated_at: '2024-03-12T14:24:29.000000Z',
// 								is_top_level: 0,
// 							},
// 						],
// 						candidates: [
// 							{
// 								id: 54,
// 								uuid: '1513e4f9-aeae-4ace-94bb-e760e3539574',
// 								organization_id: 44,
// 								job_id: 111,
// 								pipeline_stage_id: 1,
// 								first_name: 'Kitra',
// 								position: 0,
// 								last_name: 'Camacho',
// 								address: '1',
// 								email: 'mebizak@mailinator.com',
// 								phone: '1',
// 								resume_path: 'https://ik.imagekit.io/peopleplus/Image_yKCO5uM_S.pdf',
// 								resume_html_content: null,
// 								gpt_thread_id: null,
// 								image: 'https://ui-avatars.com/api/?name=Kitra Camacho&size=250',
// 								status: 'Applied',
// 								created_at: '2024-03-11T12:06:38.000000Z',
// 								updated_at: '2024-03-11T12:06:45.000000Z',
// 								deleted_at: null,
// 								timezone: '0',
// 							},
// 							{
// 								id: 56,
// 								uuid: '371d4a00-a57b-482e-9fc1-3b03fb6a3b4e',
// 								organization_id: 44,
// 								job_id: 107,
// 								pipeline_stage_id: 5,
// 								first_name: 'Stuart',
// 								position: 0,
// 								last_name: 'Ingram',
// 								address: '1',
// 								email: 'pypyfazulo@mailinator.com',
// 								phone: '1',
// 								resume_path: 'https://ik.imagekit.io/peopleplus/Image_0Fq591eAS.pdf',
// 								resume_html_content: null,
// 								gpt_thread_id: null,
// 								image: 'https://ui-avatars.com/api/?name=Stuart Ingram&size=250',
// 								status: 'Applied',
// 								created_at: '2024-03-11T12:46:32.000000Z',
// 								updated_at: '2024-03-21T08:56:32.000000Z',
// 								deleted_at: null,
// 								timezone: '0',
// 							},
// 							{
// 								id: 61,
// 								uuid: '5692bf68-a659-4d97-a35a-1fa74227138c',
// 								organization_id: 44,
// 								job_id: 107,
// 								pipeline_stage_id: 4,
// 								first_name: 'Damian',
// 								position: 0,
// 								last_name: 'Sharp',
// 								address: '1',
// 								email: 'ducogonif@mailinator.com',
// 								phone: '1',
// 								resume_path: 'https://ik.imagekit.io/peopleplus/Image_-U0buOEO0.pdf',
// 								resume_html_content: null,
// 								gpt_thread_id: null,
// 								image: 'https://ui-avatars.com/api/?name=Damian Sharp&size=250',
// 								status: 'Applied',
// 								created_at: '2024-03-12T09:48:27.000000Z',
// 								updated_at: '2024-03-21T08:56:21.000000Z',
// 								deleted_at: null,
// 								timezone: '0',
// 							},
// 						],
// 					},
// 				},
// 			})
// 		}, 500) // delay of 500ms
// 	})
// }
